server.port: 8080
spring.jpa.hibernate.ddl-auto: update
spring.jpa.show-sql: false
spring.jpa.open-in-view: true
spring.datasource.url: jdbc:mysql://#{systemEnvironment['CC_DB_HOST']}:#{systemEnvironment['CC_DB_PORT']}/#{systemEnvironment['CC_DB_NAME']}
spring.datasource.username: #{systemEnvironment['CC_DB_USER']}
spring.datasource.password: #{systemEnvironment['CC_DB_PASS']}
spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
spring.datasource.hikari.maximum-pool-size: 2
spring.main.log-startup-info: false
spring.main.allow-circular-references: true
custom.user: admin@poort.com
custom.pass: User111@!